#include "LexisType.h"

namespace code_learning {

	LexisType lexisTypes[] = {
		{LEXIS_TYPE_NONE, "LEXIS_TYPE_NONE"},
		{LEXIS_TYPE_SPACE, "LEXIS_TYPE_SPACE"},
		{LEXIS_TYPE_SYMBOL, "LEXIS_TYPE_SYMBOL"},
		{LEXIS_TYPE_DIGITAL, "LEXIS_TYPE_DIGITAL"},
		{LEXIS_TYPE_ALPHABET, "LEXIS_TYPE_ALPHABET"},
		{LEXIS_TYPE_NAME, "LEXIS_TYPE_NAME"}
	};

}
